### ISSUE TITLE
Solution file doesn't compile using submodules location

### ISSUE THREAD

**Issue by DinisCruz** [ddevault/PartyCraft#11] opened 2013-05-25 13:26 UTC
I did a clone of this repo and had to modify the partyCraft.sln file since the project files where not in the expected location.

I created a fork to hold my changes, and here is the commit https://github.com/DinisCruz/PartyCraft/commit/cee52affab4d0e12f190cf7e7b04bf3eb1d94f6c

Do you want me to do a Pull Request?

**Comment by pdelvo** [comment] 2013-05-25 13:34
It works fine for me how it is.

Did you a git clone --recursive [location]? Git will then clone submodules in and you dont have to care about doing it manually

**Comment by ddevault** [comment] 2013-05-25 16:22
Closing as cannot reproduce.

Follow @pdelvo's advice to get it compiling properly. From a clean directory, run this:

```
git clone --recursive git://github.com/SirCmpwn/PartyCraft.git
```

And then try to compile the solution.

**Closed as completed by ddevault** 2013-05-25 16:22 UTC

**Comment by DinisCruz** [comment] 2013-05-25 21:18
The problem is here https://github.com/SirCmpwn/PartyCraft/blob/master/PartyCraft.sln#L8 where it is set to 

"Craft.Net", "..\Craft.Net\Craft.Net\Craft.Net.csproj",

which means that it is looking for the Craft.Net folder on the parent folder of the clone
